name: Train/Test MNIST Sequential Model

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # allow manual triggering

jobs:
  test-mnist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🦀 Use latest toolchain
        run: rustup update

      - name: 📜 Check format
        run: cargo fmt --check

      - name: ⚙️ Install required system dependencies
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev pkg-config

      - name: 🧪 Run specific MNIST training test
        env:
          RUST_BACKTRACE: full
        run: |
          cargo test test_sequential_mnist_training -- --nocapture
